server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: coffee
          uri: http://localhost:8081
          predicates:
            - Path=/coffees/**
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**
        - id: make
          uri: http://localhost:8084
          predicates:
            - Path=/makes/**
        - id: orderDashboard
          uri: http://localhost:8085
          predicates:
            - Path=/orderDashboards/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
                - "*"
            allowCredentials: true

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: coffee
          uri: http://coffee:8080
          predicates:
            - Path=/coffees/**
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**
        - id: make
          uri: http://make:8080
          predicates:
            - Path=/makes/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080